### ISSUE TITLE
checkCoachIntegrity doesn't work

### ISSUE THREAD

**Issue by AdriDevelopsThings** [regenbogen-ice/backend#5]
There are too many coach_sequences per train_vehicle. The coach integrity check seems to be broken.

**Comment by PhilippIRL** [comment]
The problem seems to be solved:
``SELECT COUNT(id) FROM coach_sequence WHERE timestamp >= CURDATE() AND timestamp < CURDATE() + INTERVAL 1 DAY;``

Yesterday: ``237``
Today: ``7``
